import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sep490_mo/app/app_notifier.dart';
import 'package:sep490_mo/app/app_state.dart';
import 'package:sep490_mo/app/router/routes.dart';
import 'package:sep490_mo/core/constants/route_constants.dart';

part 'router_provider.g.dart';

final _key = GlobalKey<NavigatorState>();

@riverpod
GoRouter router(Ref ref) {
  final appState = ref.watch(appProvider);

  return GoRouter(
    navigatorKey: _key,
    debugLogDiagnostics: kDebugMode,
    initialLocation: RouteConstants.mainFeed,
    routes: $appRoutes, // Generated by go_router_builder from routes.dart
    redirect: (context, state) {
      // If auth state is still loading/initial, maybe show splash? 
      // For now, let's handle basic authenticated/unauthenticated logic.

      final isLoggedIn = appState.maybeWhen(
        ready: (_) => true,
        orElse: () => false,
      );

      final isLoggingIn = state.uri.path == RouteConstants.signIn || 
                          state.uri.path == RouteConstants.signUp;

      if (!isLoggedIn && !isLoggingIn) {
        return RouteConstants.signIn;
      }

      if (isLoggedIn && isLoggingIn) {
        return RouteConstants.mainFeed;
      }

      return null;
    },
  );
}
